services:
  configurator:
    environment:
      DB_HOST: postgresql
      DB_PORT: 5432
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13.8
    command: []
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
